/**
 * SEO Constants and Utilities for HIFZ
 */

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://gethifz.com';
export const SITE_NAME = 'HIFZ';

export const defaultMeta = {
  title: 'HIFZ — Memorize the Quran | Free AI-Powered Learning',
  description: 'Master Quran memorization with AI-powered lessons, spaced repetition, beautiful recitations & tajweed training. Start your journey to becoming a Hafiz today — completely free.',
  keywords: [
    'hifz',
    'quran memorization',
    'quran hifz',
    'memorize quran',
    'tajweed',
    'islamic learning',
    'quran app',
    'arabic learning',
    'hafiz',
    'quran recitation',
    'spaced repetition quran',
    'learn quran online',
    'quran for beginners',
    'free quran app',
    'muslim app',
  ],
};

export const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/hifz-logo.png`,
  description: defaultMeta.description,
  sameAs: [],
};

export const webApplicationSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: SITE_NAME,
  url: SITE_URL,
  description: defaultMeta.description,
  applicationCategory: 'EducationalApplication',
  operatingSystem: 'Web',
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
  featureList: [
    'AI-powered personalized lessons',
    'Spaced repetition memorization',
    'Tajweed training with feedback',
    'Beautiful Quran recitations',
    'Progress tracking',
    'Offline support',
  ],
};

export const courseSchema = {
  '@context': 'https://schema.org',
  '@type': 'Course',
  name: 'Quran Memorization Course',
  description: 'Complete Quran memorization curriculum from beginner to hafiz',
  provider: {
    '@type': 'Organization',
    name: SITE_NAME,
    url: SITE_URL,
  },
  isAccessibleForFree: true,
  educationalLevel: 'Beginner to Advanced',
  inLanguage: ['en', 'ar'],
  teaches: [
    'Arabic alphabet',
    'Quran reading',
    'Tajweed rules',
    'Quran memorization',
    'Proper recitation',
  ],
};

// Surah names for dynamic meta — all 114 surahs
export const SURAH_NAMES: Record<number, { english: string; arabic: string; meaning: string }> = {
  1: { english: "Al-Faatiha", arabic: "الفاتحة", meaning: "The Opening" },
  2: { english: "Al-Baqara", arabic: "البقرة", meaning: "The Cow" },
  3: { english: "Aal-i-Imraan", arabic: "آل عمران", meaning: "The Family of Imraan" },
  4: { english: "An-Nisaa", arabic: "النساء", meaning: "The Women" },
  5: { english: "Al-Maaida", arabic: "المائدة", meaning: "The Table" },
  6: { english: "Al-An'aam", arabic: "الأنعام", meaning: "The Cattle" },
  7: { english: "Al-A'raaf", arabic: "الأعراف", meaning: "The Heights" },
  8: { english: "Al-Anfaal", arabic: "الأنفال", meaning: "The Spoils of War" },
  9: { english: "At-Tawba", arabic: "التوبة", meaning: "The Repentance" },
  10: { english: "Yunus", arabic: "يونس", meaning: "Jonas" },
  11: { english: "Hud", arabic: "هود", meaning: "Hud" },
  12: { english: "Yusuf", arabic: "يوسف", meaning: "Joseph" },
  13: { english: "Ar-Ra'd", arabic: "الرعد", meaning: "The Thunder" },
  14: { english: "Ibrahim", arabic: "إبراهيم", meaning: "Abraham" },
  15: { english: "Al-Hijr", arabic: "الحجر", meaning: "The Rock" },
  16: { english: "An-Nahl", arabic: "النحل", meaning: "The Bee" },
  17: { english: "Al-Israa", arabic: "الإسراء", meaning: "The Night Journey" },
  18: { english: "Al-Kahf", arabic: "الكهف", meaning: "The Cave" },
  19: { english: "Maryam", arabic: "مريم", meaning: "Mary" },
  20: { english: "Taa-Haa", arabic: "طه", meaning: "Taa-Haa" },
  21: { english: "Al-Anbiyaa", arabic: "الأنبياء", meaning: "The Prophets" },
  22: { english: "Al-Hajj", arabic: "الحج", meaning: "The Pilgrimage" },
  23: { english: "Al-Muminoon", arabic: "المؤمنون", meaning: "The Believers" },
  24: { english: "An-Noor", arabic: "النور", meaning: "The Light" },
  25: { english: "Al-Furqaan", arabic: "الفرقان", meaning: "The Criterion" },
  26: { english: "Ash-Shu'araa", arabic: "الشعراء", meaning: "The Poets" },
  27: { english: "An-Naml", arabic: "النمل", meaning: "The Ant" },
  28: { english: "Al-Qasas", arabic: "القصص", meaning: "The Stories" },
  29: { english: "Al-Ankaboot", arabic: "العنكبوت", meaning: "The Spider" },
  30: { english: "Ar-Room", arabic: "الروم", meaning: "The Romans" },
  31: { english: "Luqman", arabic: "لقمان", meaning: "Luqman" },
  32: { english: "As-Sajda", arabic: "السجدة", meaning: "The Prostration" },
  33: { english: "Al-Ahzaab", arabic: "الأحزاب", meaning: "The Clans" },
  34: { english: "Saba", arabic: "سبإ", meaning: "Sheba" },
  35: { english: "Faatir", arabic: "فاطر", meaning: "The Originator" },
  36: { english: "Yaseen", arabic: "يس", meaning: "Yaseen" },
  37: { english: "As-Saaffaat", arabic: "الصافات", meaning: "Those drawn up in Ranks" },
  38: { english: "Saad", arabic: "ص", meaning: "The letter Saad" },
  39: { english: "Az-Zumar", arabic: "الزمر", meaning: "The Groups" },
  40: { english: "Ghafir", arabic: "غافر", meaning: "The Forgiver" },
  41: { english: "Fussilat", arabic: "فصلت", meaning: "Explained in detail" },
  42: { english: "Ash-Shura", arabic: "الشورى", meaning: "Consultation" },
  43: { english: "Az-Zukhruf", arabic: "الزخرف", meaning: "Ornaments of gold" },
  44: { english: "Ad-Dukhaan", arabic: "الدخان", meaning: "The Smoke" },
  45: { english: "Al-Jaathiya", arabic: "الجاثية", meaning: "Crouching" },
  46: { english: "Al-Ahqaf", arabic: "الأحقاف", meaning: "The Dunes" },
  47: { english: "Muhammad", arabic: "محمد", meaning: "Muhammad" },
  48: { english: "Al-Fath", arabic: "الفتح", meaning: "The Victory" },
  49: { english: "Al-Hujuraat", arabic: "الحجرات", meaning: "The Inner Apartments" },
  50: { english: "Qaaf", arabic: "ق", meaning: "The letter Qaaf" },
  51: { english: "Adh-Dhaariyat", arabic: "الذاريات", meaning: "The Winnowing Winds" },
  52: { english: "At-Tur", arabic: "الطور", meaning: "The Mount" },
  53: { english: "An-Najm", arabic: "النجم", meaning: "The Star" },
  54: { english: "Al-Qamar", arabic: "القمر", meaning: "The Moon" },
  55: { english: "Ar-Rahmaan", arabic: "الرحمن", meaning: "The Beneficent" },
  56: { english: "Al-Waaqia", arabic: "الواقعة", meaning: "The Inevitable" },
  57: { english: "Al-Hadid", arabic: "الحديد", meaning: "The Iron" },
  58: { english: "Al-Mujaadila", arabic: "المجادلة", meaning: "The Pleading Woman" },
  59: { english: "Al-Hashr", arabic: "الحشر", meaning: "The Exile" },
  60: { english: "Al-Mumtahana", arabic: "الممتحنة", meaning: "She that is to be examined" },
  61: { english: "As-Saff", arabic: "الصف", meaning: "The Ranks" },
  62: { english: "Al-Jumu'a", arabic: "الجمعة", meaning: "Friday" },
  63: { english: "Al-Munaafiqoon", arabic: "المنافقون", meaning: "The Hypocrites" },
  64: { english: "At-Taghaabun", arabic: "التغابن", meaning: "Mutual Disillusion" },
  65: { english: "At-Talaaq", arabic: "الطلاق", meaning: "Divorce" },
  66: { english: "At-Tahrim", arabic: "التحريم", meaning: "The Prohibition" },
  67: { english: "Al-Mulk", arabic: "الملك", meaning: "The Sovereignty" },
  68: { english: "Al-Qalam", arabic: "القلم", meaning: "The Pen" },
  69: { english: "Al-Haaqqa", arabic: "الحاقة", meaning: "The Reality" },
  70: { english: "Al-Ma'aarij", arabic: "المعارج", meaning: "The Ascending Stairways" },
  71: { english: "Nooh", arabic: "نوح", meaning: "Noah" },
  72: { english: "Al-Jinn", arabic: "الجن", meaning: "The Jinn" },
  73: { english: "Al-Muzzammil", arabic: "المزمل", meaning: "The Enshrouded One" },
  74: { english: "Al-Muddaththir", arabic: "المدثر", meaning: "The Cloaked One" },
  75: { english: "Al-Qiyaama", arabic: "القيامة", meaning: "The Resurrection" },
  76: { english: "Al-Insaan", arabic: "الإنسان", meaning: "Man" },
  77: { english: "Al-Mursalaat", arabic: "المرسلات", meaning: "The Emissaries" },
  78: { english: "An-Naba", arabic: "النبإ", meaning: "The Announcement" },
  79: { english: "An-Naazi'aat", arabic: "النازعات", meaning: "Those who drag forth" },
  80: { english: "Abasa", arabic: "عبس", meaning: "He frowned" },
  81: { english: "At-Takwir", arabic: "التكوير", meaning: "The Overthrowing" },
  82: { english: "Al-Infitaar", arabic: "الانفطار", meaning: "The Cleaving" },
  83: { english: "Al-Mutaffifin", arabic: "المطففين", meaning: "Defrauding" },
  84: { english: "Al-Inshiqaaq", arabic: "الانشقاق", meaning: "The Splitting Open" },
  85: { english: "Al-Burooj", arabic: "البروج", meaning: "The Constellations" },
  86: { english: "At-Taariq", arabic: "الطارق", meaning: "The Morning Star" },
  87: { english: "Al-A'laa", arabic: "الأعلى", meaning: "The Most High" },
  88: { english: "Al-Ghaashiya", arabic: "الغاشية", meaning: "The Overwhelming" },
  89: { english: "Al-Fajr", arabic: "الفجر", meaning: "The Dawn" },
  90: { english: "Al-Balad", arabic: "البلد", meaning: "The City" },
  91: { english: "Ash-Shams", arabic: "الشمس", meaning: "The Sun" },
  92: { english: "Al-Lail", arabic: "الليل", meaning: "The Night" },
  93: { english: "Ad-Dhuhaa", arabic: "الضحى", meaning: "The Morning Hours" },
  94: { english: "Ash-Sharh", arabic: "الشرح", meaning: "The Consolation" },
  95: { english: "At-Tin", arabic: "التين", meaning: "The Fig" },
  96: { english: "Al-Alaq", arabic: "العلق", meaning: "The Clot" },
  97: { english: "Al-Qadr", arabic: "القدر", meaning: "The Power, Fate" },
  98: { english: "Al-Bayyina", arabic: "البينة", meaning: "The Evidence" },
  99: { english: "Az-Zalzala", arabic: "الزلزلة", meaning: "The Earthquake" },
  100: { english: "Al-Aadiyaat", arabic: "العاديات", meaning: "The Chargers" },
  101: { english: "Al-Qaari'a", arabic: "القارعة", meaning: "The Calamity" },
  102: { english: "At-Takaathur", arabic: "التكاثر", meaning: "Competition" },
  103: { english: "Al-Asr", arabic: "العصر", meaning: "The Declining Day, Epoch" },
  104: { english: "Al-Humaza", arabic: "الهمزة", meaning: "The Traducer" },
  105: { english: "Al-Fil", arabic: "الفيل", meaning: "The Elephant" },
  106: { english: "Quraish", arabic: "قريش", meaning: "Quraysh" },
  107: { english: "Al-Maa'un", arabic: "الماعون", meaning: "Almsgiving" },
  108: { english: "Al-Kawthar", arabic: "الكوثر", meaning: "Abundance" },
  109: { english: "Al-Kaafiroon", arabic: "الكافرون", meaning: "The Disbelievers" },
  110: { english: "An-Nasr", arabic: "النصر", meaning: "Divine Support" },
  111: { english: "Al-Masad", arabic: "المسد", meaning: "The Palm Fibre" },
  112: { english: "Al-Ikhlaas", arabic: "الإخلاص", meaning: "Sincerity" },
  113: { english: "Al-Falaq", arabic: "الفلق", meaning: "The Dawn" },
  114: { english: "An-Naas", arabic: "الناس", meaning: "Mankind" },
};

export function getSurahMeta(surahNumber: number) {
  const surah = SURAH_NAMES[surahNumber];
  if (!surah) {
    return {
      title: `Surah ${surahNumber} | HIFZ`,
      description: `Read and memorize Surah ${surahNumber} with HIFZ's AI-powered learning tools.`,
    };
  }
  return {
    title: `${surah.english} (${surah.arabic}) | HIFZ`,
    description: `Read, listen, and memorize ${surah.english} - "${surah.meaning}" with beautiful recitations and tajweed guidance.`,
  };
}
